spring.application.name=demo
server.port = 8090
# Config base de datos
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/Proyecto
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
#   Tambien podria ser: create, y despues usamos update
#    create-drop   crea tablas y las elimina al terminar la ejecucion

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=franciscoriquelmenunez2@gmail.com
spring.mail.password=nmvg fesc zupr xhkp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true